"""add is_hidden to voice_sessions

Revision ID: bc395b6e2991
Revises:
Create Date: 2026-01-26 22:28:09.737129

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc395b6e2991'
down_revision: str | None = "000000000000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'voice_sessions',
        sa.Column(
            'is_hidden', sa.Boolean(),
            nullable=False, server_default='0',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_sessions', 'is_hidden')
    # ### end Alembic commands ###
